### ISSUE TITLE
Fonts, Media, Colours and Icons

### ISSUE THREAD

**Issue by Will-Sweaney** [TLDPD-01/Stars-Salon-Web-Project#6]
## Sources for fonts, media and icons

 - Icons
     - [Material UI Icons](https://mui.com/material-ui/material-icons/)
 - Media
     - [Pexels](https://www.pexels.com/)
     - Photos taken by us or the salon
 - Fonts
     -  [Google Fonts](https://fonts.google.com/)

**Comment by Finley-Borlace** [comment]
I will begin working on this

**Comment by Will-Sweaney** [comment]
Add this to the base css file, ive added some temporary values so you can work off these. 


```css
:root {
    --primary-50: #ebebfc;
    --primary-100: #c5c5f7;
    --primary-200: #9797f0;
    --primary-300: #6363df;
    --primary-400: #4c4ccf;
    --primary-500: #3535a8;
    --primary-600: #28288d;
    --primary-700: #1c1c8a;
    --primary-800: #181857;
    --primary-900: #16163b;

    --neutral-50: #f8f8f8;
    --neutral-100: #dddddd;
    --neutral-200: #c2c2c2;
    --neutral-300: #b9b9b9;
    --neutral-400: #969696;
    --neutral-500: #787878;
    --neutral-600: #5e5e5e;
    --neutral-700: #444444;
    --neutral-800: #363636;
    --neutral-900: #272727;

    --text-primary: #111111;
    --text-secondary: #252525;
    --text-tertiary: #464646;

    --card-padding: 15px;
    --card-radius: 0.5rem;

    --fontsize-h1: 48px;
    --fontsize-h2: 40px;
    --fontsize-h3: 32px;
    --fontsize-h4: 24px;
    --fontsize-body: 20px;
    --fontsize-body-sm: 16px;
    --fontsize-subtitle: 12px;
    --fontsize-subtitle-sm: 8px;
}
```
